### ISSUE TITLE
移动端展开菜单无法取消

### ISSUE THREAD

**Issue by qbsky** [Tokinx/Wing#108]
由于使用了Aplayer音乐播放器插件，必须关闭PJAX来增强兼容性。但是移动端点开导航菜单以后，再点空白处无法收回菜单bug。

**Comment by Tokinx** [comment]
麻烦提供一下：
url地址、系统、浏览器等信息

**Comment by Tokinx** [comment]
此外导航菜单能否关于与PJAX无关

**Comment by qbsky** [comment]
https://qbluesky.com/debian11 宝塔面板
via
测试过开启PJAX功能正常，关闭就不行。但是开启PJAX后，Hermit X 播放器插件就无法工作了。
&nbsp;


玉碗
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月18日(星期四) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tokinx/Wing] 移动端展开菜单无法取消 (Issue #108)





 
麻烦提供一下：
 url地址、系统、浏览器等信息

**Comment by qbsky** [comment]
https://qbluesky.com/
debian11 宝塔面板
via
测试过开启PJAX功能正常，关闭就不行。但是开启PJAX后，Hermit X 播放器插件就无法工作了。
