### ISSUE TITLE
这是个BUG吗

### ISSUE THREAD

**Issue by jiandan2020** [Tokinx/Wing#11]
![IMG_20220523_164347](https://user-images.githubusercontent.com/61310230/169780658-fda131f2-b8c1-4777-b46b-7ed7c83e4a11.jpg)
上面头像显示下面不显示

**Comment by Tokinx** [comment]
是不是配置了Gravatar的CDN地址

**Comment by jiandan2020** [comment]
> 是不是配置了Gravatar的CDN地址

是的

**Comment by Tokinx** [comment]
> > 是不是配置了Gravatar的CDN地址
> 
> 是的

从新从git拉一下主题吧，修复了这个bug
