### ISSUE TITLE
笔记上传图片BUG之Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by yucongshub** [Tokinx/Wing#116]
看到有人在讨论中遇到了这个问题，但是没有给出详细的解决办法，我这里说说吧。我产生这个问题的原因是，复制粘贴图片到笔记中，出现的是URL，于是叉掉了图片。在提交笔记后就报错无法刷出笔记内容了。报错的原因是笔记的请求返回内容内容不是json，如图
![5`JXCYNL FF 4E5@7 ~}ABT](https://github.com/Tokinx/Wing/assets/62985119/61a4cddc-e678-44f7-a800-c3c9140a01be)
![image](https://github.com/Tokinx/Wing/assets/62985119/4f1574e4-02f0-47e0-978f-db29a809dce2)
![image](https://github.com/Tokinx/Wing/assets/62985119/de92b155-c883-4ba2-963d-38294146a03c)

第一行返回了异常，根据提示的代码到服务器上查看120，121行，是需要读取这两个属性，但因为实际没有这个图片，所以是为空。我php能力有限，先注释了这两行代码，让笔记能够显示，然后在笔记中删除了这条内容，笔记显示如下图：
![I8${56W5{` XY$J6)KVUV)8](https://github.com/Tokinx/Wing/assets/62985119/2d2ca690-dfe0-45ae-ba1a-ae1cd3bca899)
在删除之前测试打开看到请求是404的，无此图片

希望作者兄弟能够解决下

**Comment by Tokinx** [comment]
比较奇怪的是，主题的编辑器实际上是无法直接使用快捷键粘贴图片的

**Comment by Tokinx** [comment]
已经尝试修复该问题，0.7.34已推送更新
