### ISSUE TITLE
笔记出现错误

### ISSUE THREAD

**Issue by pipuwong** [Tokinx/Wing#125]
我发表了一个笔记，然后在后台（媒体库）不小心把笔记的配图删了，现在页面出现错误提示：Cannot read properties of undefined (reading 'get')。请问如何解决？？

我尝试过在媒体库重新上传图片，但无果。

**Comment by 18180183837** [comment]
遇到上面同样的问题

**Comment by Tokinx** [comment]
刚测试，忘记哪个版本修复的了忘记关issue，更新到最新版即可。
