### ISSUE TITLE
Markdown语法显示问题

### ISSUE THREAD

**Issue by rand-wind** [Tokinx/Wing#139]
# 设备信息
  Windows11、Android10
  # 浏览器信息
  Microsoft Edge、Chrome、Firefox
  版本 122.0.2365.92 、123.0.6312.59、124.0

wp使用的是WP Githuber MD插件来实现markdown写作，使用表格语法制作的表格在文章内不显示边框，并且在移动端存在文字溢出

具体语法如下：

| 类别 | 网络地址范围 | 主机地址范围 | 子网掩码 |
| :--: | :---------: | :---------: | :-----: |
| A类 | 1.0.0.0 - 126.255.255.254 | 0.0.0.1 - 255.255.255.254 | 255.0.0.0 |
| B类 | 128.0.0.0 - 191.255.255.254 | 0.0.0.1 - 255.255.255.254 | 255.255.0.0 |
| C类 | 192.0.0.0 - 223.255.255.254 | 0.0.0.1 - 255.255.255.254 | 255.255.255.0 |

PC显示效果：
![屏幕截图 2024-03-23 074918](https://github.com/Tokinx/Wing/assets/78027533/bb00f1e3-2dab-403c-950b-889f4b8172b7)

移动端显示效果：
![Screenshot_20240323_080156](https://github.com/Tokinx/Wing/assets/78027533/3fcaf0c6-a15a-45e0-b4cd-7b1056aa65c2)

在表格结束后，也就是“此外......”这句话和表格之间应该有一个空行，也没有显示，贴在一起了。

示例页面：https://randwind.com/technology/ipv4-vs-ipv6_687/

不知道是什么问题。

**Comment by Tokinx** [comment]
已修复，0.8.1 更新已推送，如果收不到的话建议手动从Github下载代码更新下哈。

**Comment by Tokinx** [comment]
效果如下：
<img width="475" alt="image" src="https://github.com/Tokinx/Wing/assets/4526339/99f38173-503a-4204-9301-7b19973eeaac">

**Comment by rand-wind** [comment]
> 已修复，0.8.1 更新已推送，如果收不到的话建议手动从Github下载代码更新下哈。

大佬这效率
