### ISSUE TITLE
使用markdown撰写文章的不同级别标题的呈现问题

### ISSUE THREAD

**Issue by lazygoat644** [Tokinx/Wing#17]
rt，比如2、3、4级别的标题，在文章编辑器的界面是一个标题一行的呈现状态，在文章发布后全部排版在了一起，求大佬解决。
编辑器：
<img width="833" alt="iShot_2022-06-08_14 38 02" src="https://user-images.githubusercontent.com/25381858/172548780-909281d9-1726-44f7-8f58-fa95a3e71d72.png">
发布后：
<img width="935" alt="iShot_2022-06-08_14 38 17" src="https://user-images.githubusercontent.com/25381858/172548806-2faa23ff-f1ff-487f-a81b-a9c7dc2b9e74.png">
原文链接：
https://www.lazygoat644.xyz/2022/643/

**Comment by Tokinx** [comment]
已经修复，更新已经推送了
