### ISSUE TITLE
文章设置斜体，会自动设置高亮，但似乎没办法取消？

### ISSUE THREAD

**Issue by lazygoat644** [Tokinx/Wing#2]
<img width="171" alt="iShot2022-05-02_13 49 55" src="https://user-images.githubusercontent.com/25381858/166190273-fbc3f96a-c595-4644-baa9-4ff52a1d38f9.png">
我试了一下，只要设置成斜体，就会变成高亮，上一个主题的模板似乎不是这样设置，想知道这个是bug，还是说，是新主题的特征？

环境：
wordpress 5.9.3
php 8.0

链接：
https://www.lazygoat644.xyz/music/

**Comment by lazygoat644** [comment]
以及，还有一个问题，就是图片如果想要以一定比例缩放，比如25%，编辑界面设置好了，但是到页面展示的时候，变为自动适应页面宽度的情况。
这是编辑界面：
<img width="496" alt="iShot2022-05-02_13 56 06" src="https://user-images.githubusercontent.com/25381858/166190789-9184dddb-fd90-4b60-9043-6d49f517b1bb.png">
<img width="1294" alt="iShot2022-05-02_13 55 55" src="https://user-images.githubusercontent.com/25381858/166190793-448b57e6-7b6c-44f4-8a37-42450890de0b.png">
这是页面实际呈现的效果：
<img width="1286" alt="iShot2022-05-02_13 56 29" src="https://user-images.githubusercontent.com/25381858/166190819-d42ef17c-4a62-4d3f-b5b4-a6330a3c120c.png">

**Comment by lazygoat644** [comment]
以及，还有两个问题😂😂
一个是，wordpress新版编辑器，可以直接在图片下方插入备注，但是页面呈现的效果与实际上有点不一样，这个备注原本应该是居中的，但是在页面呈现的效果变成了左侧对齐。
编辑：
<img width="1062" alt="iShot2022-05-02_14 11 02" src="https://user-images.githubusercontent.com/25381858/166192080-b8abce0b-2424-4a87-b2be-2e7e99ec1820.png">
页面呈现效果：
<img width="957" alt="iShot2022-05-02_14 11 30" src="https://user-images.githubusercontent.com/25381858/166192098-1b7c7b6a-6232-415c-baa1-334685dc844f.png">

另一个是，表格的框线似乎在页面呈现之后消失了。。。
编辑：
<img width="982" alt="iShot2022-05-02_14 11 13" src="https://user-images.githubusercontent.com/25381858/166192155-e409875f-75a4-4196-b7fe-e8bac06ce0d9.png">
页面呈现效果：
<img width="961" alt="iShot2022-05-02_14 11 40" src="https://user-images.githubusercontent.com/25381858/166192183-3c121dee-c0e8-4541-ab8b-fca709b87f22.png">

链接：
https://www.lazygoat644.xyz/2022/406/

还请大佬帮忙查看一下😂😂

**Comment by Tokinx** [comment]
> <img alt="iShot2022-05-02_13 49 55" width="171" src="https://user-images.githubusercontent.com/25381858/166190273-fbc3f96a-c595-4644-baa9-4ff52a1d38f9.png">
> 
> 我试了一下，只要设置成斜体，就会变成高亮，上一个主题的模板似乎不是这样设置，想知道这个是bug，还是说，是新主题的特征？
> 环境： wordpress 5.9.3 php 8.0
> 
> 链接： https://www.lazygoat644.xyz/music/

这是主题特性

**Comment by Tokinx** [comment]
文章中图片、表格的样式问题，我会记录下来后面看看如何调整

**Comment by lazygoat644** [comment]
以及，还有一个问题。网站上有一些从旧版wordpress导出的文章，这些文章之前使用的是经典编辑器。我看了一下，在首页的文章列表查看到这些文章的时候，它们的缩略图（图片or文字）没有办法被抓取到，然后报错显示 : Trying to access array offset on value of type bool in /*/wp-content/themes/Wing-preview/inc/core.php on line 199，想问一下有没有可以解决的办法，或者？

链接：
https://www.lazygoat644.xyz/category/notes/page/4/

**Comment by Tokinx** [comment]
> 以及，还有一个问题。网站上有一些从旧版wordpress导出的文章，这些文章之前使用的是经典编辑器。我看了一下，在首页的文章列表查看到这些文章的时候，它们的缩略图（图片or文字）没有办法被抓取到，然后报错显示 : Trying to access array offset on value of type bool in /*/wp-content/themes/Wing-preview/inc/core.php on line 199，想问一下有没有可以解决的办法，或者？
> 
> 链接： https://www.lazygoat644.xyz/category/notes/page/4/

1、图片尺寸
2、文章缩略图问
以上两个问题已尝试修复。可以更新一下preview

**Comment by lazygoat644** [comment]
大佬，又发现了一个问题，新增加的笔记页面，在夜晚模式下，文章的标题显示的颜色有点异常~
<img width="674" alt="iShot2022-05-03_21 43 33" src="https://user-images.githubusercontent.com/25381858/166464520-b36bfcc4-e2a7-43de-a0a1-895646f68c37.png">
<img width="661" alt="iShot2022-05-03_21 43 18" src="https://user-images.githubusercontent.com/25381858/166464529-e137a826-8c29-4c75-a322-04d066e2aa88.png">

**Comment by Tokinx** [comment]
> 大佬，又发现了一个问题，新增加的笔记页面，在夜晚模式下，文章的标题显示的颜色有点异常~ <img alt="iShot2022-05-03_21 43 33" width="674" src="https://user-images.githubusercontent.com/25381858/166464520-b36bfcc4-e2a7-43de-a0a1-895646f68c37.png"> <img alt="iShot2022-05-03_21 43 18" width="661" src="https://user-images.githubusercontent.com/25381858/166464529-e137a826-8c29-4c75-a322-04d066e2aa88.png">

已修复

**Comment by lazygoat644** [comment]
大佬，又有个问题，文章评论无法直接输入文字，需要先插入一个表情然后才能输入，请求大佬排查一下~
<img width="948" alt="iShot2022-05-08_00 02 36" src="https://user-images.githubusercontent.com/25381858/167262463-554d6821-9397-41e5-bdf4-c432e6e1f59f.png">
链接：
https://www.lazygoat644.xyz/2022/593/

**Comment by Tokinx** [comment]
> 以及，还有两个问题😂😂 一个是，wordpress新版编辑器，可以直接在图片下方插入备注，但是页面呈现的效果与实际上有点不一样，这个备注原本应该是居中的，但是在页面呈现的效果变成了左侧对齐。 编辑： <img alt="iShot2022-05-02_14 11 02" width="1062" src="https://user-images.githubusercontent.com/25381858/166192080-b8abce0b-2424-4a87-b2be-2e7e99ec1820.png"> 页面呈现效果： <img alt="iShot2022-05-02_14 11 30" width="957" src="https://user-images.githubusercontent.com/25381858/166192098-1b7c7b6a-6232-415c-baa1-334685dc844f.png">
> 
> 另一个是，表格的框线似乎在页面呈现之后消失了。。。 编辑： <img alt="iShot2022-05-02_14 11 13" width="982" src="https://user-images.githubusercontent.com/25381858/166192155-e409875f-75a4-4196-b7fe-e8bac06ce0d9.png"> 页面呈现效果： <img alt="iShot2022-05-02_14 11 40" width="961" src="https://user-images.githubusercontent.com/25381858/166192183-3c121dee-c0e8-4541-ab8b-fca709b87f22.png">
> 
> 链接： https://www.lazygoat644.xyz/2022/406/
> 
> 还请大佬帮忙查看一下😂😂

文章格式问题已经着手优化了，晚上提交下。

**Comment by Tokinx** [comment]
古腾堡文章格式我适配了一下，目前这个issue下的问题应该都陆续修复了，你看下可有问题，我先关闭issue了，有新的问题可以提新的issue
