### ISSUE TITLE
评论区的代码框 超出范围

### ISSUE THREAD

**Issue by blblank** [Tokinx/Wing#21]
![0E18BB5B-716F-4FB6-AAEC-9F38F853E322](https://user-images.githubusercontent.com/38033532/176983066-e57212f9-4fe9-4ba3-9c71-446f7c77b794.png)
![D841F1AF-2911-46DD-8691-BC7BE9EF9811](https://user-images.githubusercontent.com/38033532/176983070-b1cdff22-1d88-4572-bd70-7d17648ad3e3.png)

高亮代码 建议改用 Highlight.js

**Comment by anyshift** [comment]
貌似识别设备识别的Mac OS的版本都是10.15.7。或者这是我的原因？因为我的就是10.15.7。代码超出范围框的确很明显，另外代码高亮我也建议改用Highlight.js

**Comment by Tokinx** [comment]
等我新电脑到了，我看看优化代码高亮吧，我先记一下

**Comment by Tokinx** [comment]
v0.7.20 fixed
