### ISSUE TITLE
图片灯箱问题

### ISSUE THREAD

**Issue by huhexian** [Tokinx/Wing#22]
如果文中的图片链接到“媒体文件”，则点击图片的同时会自动跳转到图片地址，这种除了取消图片链接到“媒体文件”，还有别的方法解决吗？

**Comment by Tokinx** [comment]
嗯，我这个的话，我想想办法
如果链接到一个不是图片格式的地址，我就不适用灯箱展示？这样的话灯箱需要判断是不是图片后缀，不太妥当
或者你手动排除这个媒体呢？
如果你有好的想法和建议也可以讲一下
