### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by huhexian** [Tokinx/Wing#25]
首页自动翻页，可不可以设置为仅自动翻前几页，不然文章多的博客一直往下滑，滑不完...

另外，主题每次更新，认证读者那填的邮箱，是不是会被清空？

**Comment by Tokinx** [comment]
应该不会清空吧，不然其它设置按理说应该会重新设置？（比如Bark Key也没清空）。我记录一下，下次更新我看看有没有清空掉

翻页的问题，笔记类型确实就是这样，看文章会切换到分类呀。我记录一下，不确定会不会加这个滚动次数
