### ISSUE TITLE
嗨，请问如何在前台发布对象存储链接的照片呢，前台是直接询问本地文件，谢谢

### ISSUE THREAD

**Issue by axiomxs** [Tokinx/Wing#26]
嗨，请问如何在前台发布对象存储链接的照片呢，前台是直接询问本地文件，谢谢

**Comment by Tokinx** [comment]
主题调用的是WP自带的图片上传接口，如果你使用的对象存储插件已经覆盖了wp文件上传的hook，那主题也会支持。
如果插件不支持，可能需要你使用子主题模式进行二次开发
