### ISSUE TITLE
笔记模块页面错误提示，无法获取笔记数量、文章数量

### ISSUE THREAD

**Issue by Road09** [Tokinx/Wing#4]
作者好，在使用设计笔记主题时，发现Cannot read properties of undefined
(reading 'get')提示，右侧的记录模块无法调取统计笔记、文章数量，话题模块显示为代码模块。

如图：

<img width="1675" alt="WX20220503-190239@2x" src="https://user-images.githubusercontent.com/83681438/166442599-383255a8-9642-45cd-b6e9-85dd4fc2a92a.png">

页面地址：https://www.waistu.com/note

另外笔记前端编辑功能似乎也无法使用，期待早日修复！

**Comment by Road09** [comment]
话题位置显示代码经过测试为bitbox插件冲突，已禁用插件，但其他问题仍然存在

**Comment by Tokinx** [comment]
主题目录下的cache文件夹需要给一下读写权限。
