### ISSUE TITLE
文章内代码块没有横向滚动条导致代码溢出

### ISSUE THREAD

**Issue by gorkys** [Tokinx/Wing#47]
![image](https://user-images.githubusercontent.com/29664101/189816921-9215ce40-fe49-4220-b1a7-477bfaf42511.png)

**Comment by gorkys** [comment]
F12后在对应css中加入可解决：
```
body pre{
     ...
     overflow: auto;
}
```

**Comment by Tokinx** [comment]
v0.7.21 fixed，晚些时候会推送更新
唉，这个代码段之前是有些样式的，但是后来wp升级后提供了样式，主题就给去掉了。。
没想到wp现在又把默认样式去掉了，导致现在这个问题。。。默默把代码段样式加回来。。。
