### ISSUE TITLE
话题标签会带有空格字符

### ISSUE THREAD

**Issue by minisix** [Tokinx/Wing#50]
写笔记设置的话题标签在右边栏显示时会带有空格字符，请问一下如何修改？谢谢~

**Comment by Tokinx** [comment]
使用的是什么浏览器呢，浏览器版本、WordPress版本，主题版本是什么呢，我排查一下。

**Comment by minisix** [comment]
WordPress版本:6.0.2, Chrome版本 105.0.5195.125（正式版本）主题Wing版本：0.7.21

**Comment by Tokinx** [comment]
有截图或者网站吗、我没找到复现路径。

**Comment by 7fffan** [comment]
![image](https://user-images.githubusercontent.com/119554802/210161695-2f4bc44e-372e-4f82-a9a1-6e80ded9fa71.png)

> 有截图或者网站吗、我没找到复现路径。

**Comment by Tokinx** [comment]
> ![image](https://user-images.githubusercontent.com/119554802/210161695-2f4bc44e-372e-4f82-a9a1-6e80ded9fa71.png)
> 
> > 有截图或者网站吗、我没找到复现路径。

我看看做一下兼容处理吧，如果有空格字符就替换成空

**Comment by minisix** [comment]
Hi,


很抱歉现在才回复邮件, Sorrrrry...
之前使用因为有几个bug，一度wordpress后台也无法进入，所以就没再使用了。


因为使用的是多站点，各种各样的兼容问题吧，自己不懂代码，不一定是你主题造成的。


安装主题除了话题标签有空格符，还有手机浏览器（Kiwi）无法显示站点页面。
另外一个主要原因是：主题目前无法在后台管理发布的笔记，所以放弃了。


很抱歉没能帮助到你。


Joy






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tokinx/Wing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月4日(星期三) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tokinx/Wing] 话题标签会带有空格字符 (Issue #50)





  

  
有截图或者网站吗、我没找到复现路径。
   
我看看做一下兼容处理吧，如果有空格字符就替换成空
