### ISSUE TITLE
作者老哥，一些小建议

### ISSUE THREAD

**Issue by axiomxs** [Tokinx/Wing#52]
作者老哥，您看看 memos 这个项目的 输入框 和 图片样式 ，感觉很好看

**Comment by axiomxs** [comment]
老哥，能不能默认把主题全局放大110%，这样的话，字体就会很饱满，阅读观感很好

**Comment by Tokinx** [comment]
> 老哥，能不能默认把主题全局放大110%，这样的话，字体就会很饱满，阅读观感很好

如果喜欢偏饱满一点的风格，可以在主题-自定义-额外CSS里添加下面代码：

```
html {
	font-size: 24px;
}
```
主题默认基础大小为20px，你可以根据喜好自行调整控制。

**Comment by Tokinx** [comment]
memos更像是私有化部署的flomo，但是有一点遗憾的是主题使用的是可视化编辑器，memos是markdown，暂时没有很多精力来迁移或完善这部分。
