### ISSUE TITLE
🎉 图片上传拓展为【任意文件上传】

### ISSUE THREAD

**Issue by Tokinx** [Tokinx/Wing#69]
🎉 图片上传拓展为【任意文件上传】
自动解析图片、视频匹配样式，对于无法预览的文件，展示下载链接与样式
Inspired by Memos

**Comment by axiomxs** [comment]
好欸

**Comment by axiomxs** [comment]
作者带带，https://demos.buddyboss.com/online-communities/#
这个主题的输入框还不错欸
