### ISSUE TITLE
手机端图片错位

### ISSUE THREAD

**Issue by 7fffan** [Tokinx/Wing#94]
系统：安卓
版本：10
浏览器：夸克
![63a7dbf19ee1c.jpg](https://pic.liesys.com/i/2022/12/25/63a7dbf19ee1c.jpg)

**Comment by 7fffan** [comment]
使用edg手机版，显示正常

**Comment by Tokinx** [comment]
好像是因为夸克的浏览器内核问题导致的，可能是版本低或者魔改的内核，这个地方最近要调整，到时候一起修复
